import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import maxProfit from '@/utils/evaluarPrecios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [resultado, setResultado] = useState('')
  const [precios, setPrecios] = useState('')

  const evalularPrecios = () => {
    const gananciaMaxima = maxProfit(precios.split(",").map(e => Number(e.trim())))
    setResultado(`La ganancia máxima es de ${gananciaMaxima}`)
  }

  const handleInputChange = (e) => {
    const v = e.target.value
    if (/^[0-9,.]*$/.test(v)) {
      setPrecios(v)
    }

  }
  return (
    <>
      <Head>
        <title>Proyecto de IS2</title>
        <meta name="description" content="Generated by Proyecto de IS2" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="input-group mb-3 mt-3">
        <span
          className="input-group-text"
          id="basic-addon1"
        >
          Entrada de precios separados por coma
        </span>
        <input
          type="text"
          className="form-control"
          placeholder="precios"
          aria-label="precios"
          value={precios}
          onChange={handleInputChange}
        />
      </div>

      <button type="button" className="btn btn-primary" onClick={evalularPrecios}>Evaluar</button>

      <div className="resultado">
        {resultado}
      </div>
      </main>
    </>
  )
}
